name: "Code style"

on:
  pull_request:
    paths:
      - "**.php"
      - ".php-cs-fixer.dist.php"
      - ".github/workflows/code-style.yml"

jobs:
  phpcs:
    name: "PHPCS"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository to the runner
        uses: "actions/checkout@v4"

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          tools: cs2pr

      - name: Composer install
        run: ./tools/bin/php-cs-fixer --version

      - name: Run phpcs
        run: ./tools/bin/php-cs-fixer check --show-progress=none --format=checkstyle | cs2pr
