name: Docs

on:
  push:
    branches:
      - main

    # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
    tags:
      - '*'

env:
  GITHUB_TOKEN: "x-access-token:${{ secrets.MONOREPO_GIT_TOKEN }}"

jobs:
  docs:
    name: "Generate and publish docs"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: "actions/checkout@v4"

      - name: Generate docs
        uses: "docker://phpdoc/phpdoc:3"
        with:
          workdir: '/github/workspace'
          args: 'project:run -t packages/docs/docs'

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Push main to docs
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          package_directory: "packages/docs"
          repository_organization: "php-addition-repository"
          repository_name: "php-addition-repository.github.io"
          user_name: "Alex Brouwer"
          user_email: "brouwer.alexander@gmail.com"
          branch: "main"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Push tag to docs
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: "packages/docs"
          repository_organization: "php-addition-repository"
          repository_name: "php-addition-repository.github.io"
          user_name: "Alex Brouwer"
          user_email: "brouwer.alexander@gmail.com"
          branch: "main"
