name: 'Update package repositories'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  GITHUB_TOKEN: "x-access-token:${{ secrets.MONOREPO_GIT_TOKEN }}"

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - core

    steps:
      - name: Check out the repository to the runner
        uses: "actions/checkout@v4"

      # no tag
      - if: "!startsWith(github.ref, 'refs/tags/')"
        name: Push main to ${{ matrix.package }}
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          package_directory: "packages/${{ matrix.package }}"
          repository_organization: "php-addition-repository"
          repository_name: "${{ matrix.package }}"
          user_name: "Alex Brouwer"
          user_email: "brouwer.alexander@gmail.com"
          branch: "main"

      # with tag
      - if: "startsWith(github.ref, 'refs/tags/')"
        name: Push tag to ${{ matrix.package }}
        uses: "danharrin/monorepo-split-github-action@v2.3.0"
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: "packages/${{ matrix.package }}"
          repository_organization: "php-addition-repository"
          repository_name: "${{ matrix.package }}"
          user_name: "Alex Brouwer"
          user_email: "brouwer.alexander@gmail.com"
          branch: "main"
